[[CURRENCIES]]
code="SAMIR"
issuer="GCACRRM5GQT7JWNCNWQNHU4KIUQSQ4VFNZYHRZJU6ZWAB2H6KX7KY46K"
name="samir DZD test"
desc="Test token on Pi Testnet"
image="https://samirartist.github.io/logo.png".image="https://samirartist.github.io/logo.png"
