
[[CURRENCIES]]
code="DZDGCV"
issuer="GACXBFACF7KLDDY4ZYNVNVUTSJOYDABVTT4USI2Y2Q5GXP35DKAPTGRI"
name="DZDGCV"
desc="Test token on Pi Testnet"
image="https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg"


