
[[CURRENCIES]]
code="DZDGCV"
issuer="حط المفتاح العام تاع محفظة الإصدار هنا لي يبدا بـ G"
name="DZDGCV"
desc="Test token on Pi Testnet"
image="https://raw.githubusercontent.com/USERNAME/REPO/main/logo.png"


